# Generated by Django 5.0 on 2023-12-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Знижка', 'verbose_name_plural': 'Знижки'},
        ),
    ]
