# Generated by Django 5.0 on 2023-12-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0007_books_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='size',
            field=models.CharField(default=210, max_length=20, verbose_name='Розміри'),
            preserve_default=False,
        ),
    ]
