# Generated by Django 5.0 on 2024-01-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0009_comments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image2',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Зображення 1'),
        ),
        migrations.AddField(
            model_name='books',
            name='image3',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Зображення 2'),
        ),
        migrations.AddField(
            model_name='books',
            name='image4',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Зображення 3'),
        ),
        migrations.AddField(
            model_name='books',
            name='image5',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Зображення 4'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=20, unique=True, verbose_name='Категорія'),
        ),
    ]
