# Generated by Django 5.0 on 2024-01-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0010_books_image2_books_image3_books_image4_books_image5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='uploads', verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=75, unique=True, verbose_name='Назва'),
        ),
    ]
