# Generated by Django 5.0 on 2024-01-13 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0012_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='department',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='bankCard',
            field=models.CharField(blank=True, max_length=75, verbose_name='Номер банківської картки'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='city',
            field=models.CharField(blank=True, max_length=75, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(blank=True, max_length=75, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='region',
            field=models.CharField(blank=True, max_length=75, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='zip',
            field=models.CharField(blank=True, max_length=10, verbose_name='Поштовий Індекс'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, verbose_name="Ім'я")),
                ('lastname', models.CharField(blank=True, max_length=75, verbose_name='Прізвище')),
                ('bankCard', models.CharField(blank=True, max_length=75, verbose_name='Номер банківської картки')),
                ('city', models.CharField(blank=True, max_length=75, verbose_name='Місто')),
                ('region', models.CharField(blank=True, max_length=75, verbose_name='Область')),
                ('zip', models.CharField(blank=True, max_length=10, verbose_name='Поштовий Індекс')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('notes', models.TextField(verbose_name='Коментар')),
                ('orderedBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasure.books')),
            ],
        ),
    ]
