# Generated by Django 5.0 on 2024-01-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0013_remove_userdetails_department_userdetails_bankcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orderedBook',
        ),
        migrations.AddField(
            model_name='orders',
            name='orderedBook',
            field=models.ManyToManyField(related_name='books', to='treasure.books'),
        ),
    ]
